name: CI
on:
  - push
  - pull_request
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Type checking
        run: yarn run check
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build:lib
      - name: Publish
        run: |
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
          npm publish --registry=https://npm.pkg.github.com
          npm publish --access=public
        if: startsWith(github.ref, 'refs/tags/')
